language: node_js
dist: trusty

node_js:
  - "stable"
env:
  - NODE_ENV=test
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS turing_test;'
  - chmod 0777 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
cache:
  directories:
    - "node_modules"
